version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: findafriend-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: findafriend
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 