services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: findafriend-api-dev
    restart: always
    ports:
      - 3333:3333
    environment:
      - NODE_ENV=dev
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/findafriend
      - JWT_SECRET=your-secret-key-here-change-this-in-production
      - PORT=3333
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  postgres:
    image: postgres:15
    container_name: findafriend-db-dev
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: findafriend
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: 