FROM node:18-alpine

# Instalar OpenSSL para compatibilidade com Prisma
RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3333

CMD ["npm", "run", "start:dev"] 